In [1]:
import numpy as np

In [9]:
%config Completer.use_jedi = False

![](https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays-1024x572.png)

In [4]:
arr = np.array([1, 2, 3, 4], dtype='float')
arr

array([1., 2., 3., 4.])

In [5]:
type(arr)

numpy.ndarray

- List: Mixed type, low performance
- ndarray: Single type, high performance

In [6]:
arr_2 = np.array([True, False, 1, 2, 3])
arr_2

array([1, 0, 1, 2, 3])

In [7]:
li = [1, 2, 3, 4]
li ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [8]:
arr_2**2

array([1, 0, 1, 4, 9])

- Vectorization: consider array as a number
- Broadcasting: 

![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [11]:
np.arange(3) + 5

array([5, 6, 7])

### 1. Create numpy array

In [13]:
arr = np.array([1, 2, 3], dtype='f')
arr

array([1., 2., 3.], dtype=float32)

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype='f')
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [15]:
arr.shape

(3, 3)

In [17]:
arr = np.linspace(1, 10, 11)
arr

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [20]:
arr = np.linspace(1, 10, 12).reshape(4, 3)
arr

array([[ 1.        ,  1.81818182,  2.63636364],
       [ 3.45454545,  4.27272727,  5.09090909],
       [ 5.90909091,  6.72727273,  7.54545455],
       [ 8.36363636,  9.18181818, 10.        ]])

In [21]:
arr = np.linspace(1, 10, 12).reshape(3, 2, 2)
arr

array([[[ 1.        ,  1.81818182],
        [ 2.63636364,  3.45454545]],

       [[ 4.27272727,  5.09090909],
        [ 5.90909091,  6.72727273]],

       [[ 7.54545455,  8.36363636],
        [ 9.18181818, 10.        ]]])

In [22]:
arr * 3

array([[[ 3.        ,  5.45454545],
        [ 7.90909091, 10.36363636]],

       [[12.81818182, 15.27272727],
        [17.72727273, 20.18181818]],

       [[22.63636364, 25.09090909],
        [27.54545455, 30.        ]]])

In [23]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.full((3, 4), fill_value=6, dtype='f')

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]], dtype=float32)

In [27]:
arr.shape

(3, 2, 2)

In [28]:
np.ones_like(arr)

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [29]:
np.zeros_like(arr)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [31]:
np.full_like(arr, fill_value=5)

array([[[5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.]]])

In [43]:
np.random.seed(5)
np.random.randint(1, 10, size=5)

array([4, 7, 7, 1, 9])

In [44]:
from datetime import datetime

In [65]:
time = int(datetime.now().microsecond / 1000)
random = 3 * time + 4
random

1060

In [70]:
def random(time=None):
    if time is None:
        time = int(datetime.now().microsecond / 1000)
    return 3 * time + 4

In [76]:
random(time=3)

13